name: auto_build

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     - uses: actions/setup-java@v2
       with:
         distribution: 'zulu'
         java-version: 11
      - uses: subosito/flutter-action@v2.1.0
        with:
            channel: 'stable'
      - run: sudo apt install build-essential ninja-build clang cmake pkg-config libgtk-3-dev liblzma-dev
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@master
        with:
          name: fluttervcc.apk
          path: build/app/outputs/apk/release/app-release.apk
